blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/aimd54/gitlab-reviewer-roulette/discussions
    about: Ask questions or discuss ideas with the community
  - name: GitLab Documentation
    url: https://docs.gitlab.com/ee/api/
    about: Official GitLab API documentation
